apiVersion: v2
name: environment-provider
description: Handling of environments making it possible to checkout and check in
  environments for use in testing with ETOS.
type: application
version: 2.1.3
appVersion: 1.36.0

keywords:
  - Test automation
  - Eiffel

home: https://etos.readthedocs.io/

maintainers:
  - name: Anders Josephson
    email: anders.josephson@axis.com
  - name: Fredrik Fristedt
    email: fredrik.fristedt@axis.com
  - name: Tobias Persson
    email: tobias.persson@axis.com
