version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/cli"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "etos_lib"
    groups:
      etos-lib:
        patterns:
          - "etos_lib"
