apiVersion: v2
appVersion: 1.5.0
description: Handling of environments making it possible to checkout and check in
  environments for use in testing with ETOS.
name: environment-provider
type: application
version: 1.5.0
