- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/eventRepository/properties/storage/properties/image/default
  value: "ghcr.io/eiffel-community/eiffel-graphql-storage:latest"
