- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/etos/properties/suiteRunner/properties/logListener/properties/image/default
  value: ghcr.io/eiffel-community/etos-log-listener:08850be7
