- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/etos/properties/suiteStarter/properties/image/default
  value: "ghcr.io/eiffel-community/etos-suite-starter:6b1146e1"
