apiVersion: etos.eiffel-community.github.io/v1alpha1
kind: Provider
metadata:
  labels:
    app.kubernetes.io/name: etos
    app.kubernetes.io/managed-by: kustomize
  name: execution-space-provider-sample
spec:
  type: execution-space
  image: ghcr.io/eiffel-community/execution-space-provider:v0.0.1
