apiVersion: etos.eiffel-community.github.io/v1alpha2
kind: Iut
metadata:
  labels:
    app.kubernetes.io/name: etos
    app.kubernetes.io/managed-by: kustomize
  name: iut-sample
spec:
  # TODO(user): Add fields here
