apiVersion: etos.eiffel-community.github.io/v1alpha1
kind: Provider
metadata:
  labels:
    app.kubernetes.io/name: etos
    app.kubernetes.io/managed-by: kustomize
  name: log-area-provider-sample
spec:
  type: log-area
  image: example.com/logareaprovider:v0.0.1
  logAreaProviderConfig:
    livelogs: http://cluster-sample-etos-logarea/logarea/v1alpha/$context
    upload:
      as_json: false
      method: POST
      url: http://cluster-sample-etos-logarea/logarea/v1alpha/upload
