apiVersion: etos.eiffel-community.github.io/v1alpha1
kind: TestRun
metadata:
  labels:
    app.kubernetes.io/name: etos
    app.kubernetes.io/managed-by: kustomize
  name: testrun-sample-multi-suite  # This is used by e2e test, don't change
spec:
  identity: pkg:testrun/etos/eiffel_community  # This is used by e2e test, don't change
  artifact: 268dd4db-93da-4232-a544-bf4c0fb26dac  # This is used by e2e test, don't change
  cluster: cluster-sample
  providers:
    iut: iut-provider-sample  # This is used by e2e test, don't change
    executionSpace: execution-space-provider-sample  # This is used by e2e test, don't change
    logArea: log-area-provider-sample  # This is used by e2e test, don't change
  suites:
  - name: testrun-sample
    dataset:
      test: Hello
    tests:
    - environment: {}
      execution:
        checkout:
        - git clone https://github.com/eiffel-community/etos
        command: exit 0
        environment: {}
        execute:
        - sleep 30
        parameters: {}
        testRunner: ghcr.io/eiffel-community/etos-base-test-runner:bullseye
      id: c2c93da1-53c7-42f2-881c-60a579e57630
      testCase:
        id: etos-sample-test
        version: main
  - name: testrun-sample-extra-suite
    dataset:
      test: Hello
    tests:
    - environment: {}
      execution:
        checkout:
        - git clone https://github.com/eiffel-community/etos
        command: exit 0
        environment: {}
        execute:
        - sleep 30
        parameters: {}
        testRunner: ghcr.io/eiffel-community/etos-base-test-runner:bookworm
      id: c2c93da1-53c7-42f2-881c-60a579e57630
      testCase:
        id: etos-sample-test
        version: main
