apiVersion: etos.eiffel-community.github.io/v1alpha1
kind: Provider
metadata:
  labels:
    app.kubernetes.io/name: etos
    app.kubernetes.io/managed-by: kustomize
  name: iut-provider-sample
spec:
  type: iut
  image: ghcr.io/eiffel-community/iut-provider:v0.0.1
