apiVersion: etos.eiffel-community.github.io/v1alpha1
kind: Provider
metadata:
  labels:
    app.kubernetes.io/name: etos
    app.kubernetes.io/managed-by: kustomize
  name: log-area-provider-sample
spec:
  type: log-area
  image: ghcr.io/eiffel-community/log-area-provider:v0.0.1
