apiVersion: etos.eiffel-community.github.io/v1alpha1
kind: Provider
metadata:
  labels:
    app.kubernetes.io/name: etos
    app.kubernetes.io/managed-by: kustomize
  name: iut-provider-sample
spec:
  type: iut
  image: example.com/iutprovider:v0.0.1
