## Append samples of your project ##
resources:
- etos_v1alpha1_testrun.yaml
- etos_v1alpha1_provider.yaml
- etos_v1alpha1_environment.yaml
- etos_v1alpha1_cluster.yaml
- etos_v1alpha1_environmentrequest.yaml
- etos_v1alpha2_iut.yaml
- etos_v1alpha2_executionspace.yaml
- etos_v1alpha2_logarea.yaml
