apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api/service-account.yaml
  - api/deployment.yaml
  - api/service.yaml
  - worker/service-account.yaml
  - worker/deployment.yaml


# By generating the configmap it will get a unique name on each apply
# this name is also set on the deployment. This means that the pods
# will restart with the new configmap when changes are made. Making
# it so we do not have to do rollout restart every time.
configMapGenerator:
  - name: etos-environment-provider-worker
    literals:
      - ETR_VERSION="2.4.0"
  - name: etos-environment-provider
