apiVersion: v2
appVersion: 1.18.0
description: ETOS (Eiffel Test Orchestration System) is a new test orchestration system
  which takes away control of how to run and what to run from the system itself and
  places it into the hands of the relevant engineers.
name: etos
type: application
version: 1.18.0
