apiVersion: v2
appVersion: 1.15.0
description: The ETOS Suite Starter exist solely to make sure that the ETOS system
  can be upgrade without any downtime. It listens to EiffelTestExecutionRecipeCollectionCreatedEvent
  and launches an instance of ETOS Suite runner in Kubernetes as a Job.
name: suite-starter
type: application
version: 1.15.0
